name: Jellyfin CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.8'  # Versão requerida do repositório

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish build artifacts
      run: dotnet publish --configuration Release --output ./output

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        args: >
          sonar-scanner
          -Dsonar.projectKey=lukspc_sonarcloud-github-jellyfin
          -Dsonar.organization=Lucas Pereira Cavalcante
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
